### PR TITLE
XHGui setup adjustments

### PR DESCRIPTION
**Pull request by tomjn**
make the paths explicit rather than relative for some xhgui installation steps

### CODE REVIEW

**Comment by skorasaurus** [comment]
vvv/provision/extensions/core; I ran: 
git fetch origin 
git checkout --track origin/xhgui-tweaks

my config file used for this is at https://gist.github.com/skorasaurus/9d6ecb95e5ef2d9ad05b26b2eafa6780

then `vagrant up --provision-with="extension-core-tideways"`

no immediate errors in my provision log (in console); and visiting but every page has a warning of ` Parse error: syntax error, unexpected ';' in /srv/www/default/php-profiler/config.php on line 4`

**Comment by Mte90** [comment]
Fixed the issue you found :-)

**Comment by skorasaurus** [comment]
thanks, confirmed that it fixed it.

**Comment by tomjn** [comment]
if I can get a code review then I'm happy to merge this in

@skorasaurus you can switch back to the `master` branch, or just delete the `provision/extensions/core` folder and reprovision, VVV will recreate it

**Comment by skorasaurus** [comment]
sorry to throw a wrench in this; but I reprovisioned this afternoon; (vagrant halt of my machine; then did `vagrant up --provision-with="extension-core-tideways"` 
and I noticed in the terminal log (that appears in the terminal after I press enter of `vagrant up --provision-with="extension-core-tideways"` )  includes the following [(full output)](https://gist.github.com/skorasaurus/1248c1a5b79992c6a3fdfc6ed9212ebb), `Failed to load the PHP Profiler autoloader.php file, confirm provisioning of tideways was succesful, reprovision, and if all else fails delete the php-profiler folder in /srv/www/default and report on the VVV github` 

I admittedly don't use tideways so it hasn't affected my workflow.

**Review by Mte90 — APPROVED** [review]

**Comment by tomjn** [comment]
@skorasaurus at any point had you provisioned in any other way than the `--provision-with`? The reason is that normally VVV does a hard reset forcing it back to the configured default or what `config.yml` says, so any of these changes would have been undone, and it only needs to happen _once_.

**Comment by tomjn** [comment]
@Mte90 when checking for tideways it uses phpenmod which activates tideways correct? Wouldn't this mean tideways runs on the composer provisioning steps that happen next? And are we sure that's something we want?

**Comment by tomjn** [comment]
@skorasaurus if you run it again does it still give that message?

**Comment by Mte90** [comment]
We are putting the ini files only on mods-avalaible and not in the cli folder so it is not executed on composer.

**Comment by skorasaurus** [comment]
> @skorasaurus if you run it again does it still give that message?

in the past week, I don't believe so; I thought I've started my i searched through my bash history to verify and didn't find 'vagrant up commands' that were not `"vagrant up --provision-with="extension-core-tideways"` although I don't use screen as often as I should; so all of my bash history probably isn't captured.

A few minutes ago; I did vagrant halt; shut down my computer; started it; and issued `vagrant up --provision-with="extension-core-tideways"` and this was the result

**Comment by tomjn** [comment]
@Mte90 any ideas?

**Comment by tomjn** [comment]
> We are putting the ini files only on mods-avalaible and not in the cli folder so it is not executed on composer.

Have you confirmed this? Because those ini files will make it load that PHP file, and we're seeing output from that PHP file.

I know it shouldn't but that doesn't mean it can't happen. We should guarantee it cannot happen by not installing `ini` files for software that has not been installed yet

**Comment by Mte90** [comment]
Yes we can install xhgui before tideways it isn't an issue.

**Comment by Mte90** [comment]
So we have:
```

**Comment by tomjn** [comment]
I'm going to merge this to simplify testing as this is already fixing some things, we can follow up with another PR if needed

**Pull request merged**
