### PR TITLE
TLS-CA bash functions

### PR DESCRIPTION
**Pull request by tomjn**
refactored the TLS CA to use bash functions for everything, set the certificate expiry days as variables, and moved the openssl config stuff to files

Recreates some of what was in #56, this should work the same as before, but structured better

### CODE REVIEW

**Comment by tomjn** [comment]
This now preserves the keys and CSR and instead only recreates the certificates for sites and the default, rather than deleting the whole folder and doing it from scratch

**Comment by Mte90** [comment]
Can you give some hints about what kind of tests do you need? I am on linux but I don't use https for my dev websites.

**Comment by tomjn** [comment]
It should be enough to spin up a fresh VVV instance and test that the
default sites work with the certificates

**Comment by Mte90** [comment]
how I can test it? as it is the official repo I am not sure if the branch parameter i supported

**Comment by tomjn** [comment]
It is, just add the repo and branch and name it `core`

**Comment by Mte90** [comment]
Found the documentation https://varyingvagrantvagrants.org/docs/en-US/utilities/

**Comment by Mte90** [comment]
Tested and now the browser doesn't shows any error with the certificate.

**Pull request merged**
