### PR TITLE
setup openssl options for root CA certificate

### PR DESCRIPTION
**Pull request by tomjn**
Tries to satisfy some of the Apple req by adding a config for the CA certificate

### CODE REVIEW

**Comment by tomjn** [comment]
This appears to fix things for me locally, can someone test this by doing these steps:

 - remove the root certificate authority from keychain/OS
 - delete the contents of the `certificates` folder
 - Update the VVV config file to contain this:

```yaml
utility-sources:
  core:
    repo: https://github.com/Varying-Vagrant-Vagrants/vvv-utilities.git
    branch: tls-ca-fixes
```

 - Reprovision and retrust CA root certificate
 - test HTTPS in Safari/Chrome on MacOS

**Comment by debabratakarfa** [comment]
Hi @tomjn 
I have tested with this config but getting `NET::ERR_CERT_COMMON_NAME_INVALID`

**Comment by tomjn** [comment]
@debabratakarfa and you thoroughly cleaned out certificates beforehand, and retrusted in keychain the root certificate? And tested in Safari/Chrome? I'm seeing the default sites and dashboard load fine in Safari/Chrome here. It says the root CA `VVV INTERNAL CA` is trusted, and `vvv.test` certificate is valid

**Comment by tomjn** [comment]
Updated the PR to account for https://support.apple.com/en-us/HT211025 which takes effect September 1st

**Comment by tomjn** [comment]
It also looks like a certificate can be tested in the terminal using `security verify-cert -c ca.crt`, e.g.:

```sh
~/dev/vvv/certificates/ca git::develop 
❯ security verify-cert -c ca.crt
...certificate verification successful.
```

**Comment by tomjn** [comment]
After some further investigation I've gotten the certificate to have the needed OID parameter, it's now ready for testing again

**Comment by tomjn** [comment]
I believe this is as good as or better than what we currently have, if there are fixes still needed for Catalina we can create a new PR

**Pull request merged**
