### PR TITLE
Feature/add php81

### PR DESCRIPTION
**Pull request by evantill**
Can you add php 8.1 (for testing purpose) ?

I have just copy/paste php80 core extension and replacing 8.0 by 8.1 in files

### CODE REVIEW

**Comment by evantill** [comment]
The first commit is a copy paste from php80 to php81.
The second commit is replacing 8.0 references by 8.1.

I am using it to test wordpress code in dev. Us there some tests to run ?

**Comment by tomjn** [comment]
Ooo we should prioritise this, thanks for getting the ball rolling :)

**Comment by av3nger** [comment]
@evantill, thanks! Tested, works without issues.
However, wish I haven't done that, so many deprecation notices in WordPress 🤦

**Comment by tomjn** [comment]
@evantill there's one final change that's needed, the main `php` provision.sh that installs all the others for people who just want all of them, it needs 8.1 adding too

**Comment by av3nger** [comment]
And adding `php81` to the `config/default-config.yml` file

**Comment by tomjn** [comment]
@av3nger that would be a separate PR for the main VVV repo, we can get to that once this is merged

**Review by tomjn — APPROVED** [review]
👍🏻

**Comment by evantill** [comment]
thank you

**Comment by evantill** [comment]
> And adding `php81` to the `config/default-config.yml` file

do you need a PR for that ?

**Comment by tomjn** [comment]
a PR would be nice, but it's not necessary, by merging this anyone can add `php81` and get 8.1, essentially we've shipped

**Pull request merged**
