### PR TITLE
Added NVM as a core utility

### PR DESCRIPTION
**Pull request by coolamit**
Added `nvm` provisioner as an optional core utility for VVV

Ref: https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2177

### CODE REVIEW

**Comment by tomjn** [comment]
A quick thought, does the nvm installer script also update nvm? There'll need to be another PR to the main VVV repo to remove/adjust the cleanup code there so it doesn't mess things up after this provisioner has run.

Big fan of the subfolder readme btw, we should have more of these

**Comment by Mte90** [comment]
A check in VVV that verify if the utility is not installed and execute the removal of nvm should be enough to keep compatibility.

**Comment by coolamit** [comment]
> A quick thought, does the nvm installer script also update nvm?

Yeah, `nvm` has same curl command to download & run the bash script to install & update. If `nvm` is not installed then it will install it and if an older version is installed then it will update it. Currently it installs v0.35.3 which is the latest stable version.

> There'll need to be another PR to the main VVV repo to remove/adjust the cleanup code there so it doesn't mess things up after this provisioner has run.

Yeah I already opened a [PR in VVV repo](https://github.com/Varying-Vagrant-Vagrants/VVV/pull/2185) for that.

**Comment by tomjn** [comment]
If that's the case, once it's installed it won't try to update, as it only runs the script when nvm isn't installed? Maybe I'm reading it wrong

**Comment by coolamit** [comment]
> If that's the case, once it's installed it won't try to update, as it only runs the script when nvm isn't installed?

That's correct. Once its installed, it does not interfere with `nvm` in any way.  As long as `~/.nvm` directory exists & it has `~/.nvm/nvm.sh` file, this won't run again.

So that way, if someone has already installed `nvm` - we wouldn't want to mess with their installation. And if someone updates `nvm` on their own then their installation wouldn't get messed either.

**Comment by tomjn** [comment]
I'm not able to test this at the moment, lightning destroyed my networking equipment so I can't run a provision of this

**Comment by Mte90** [comment]
# Log file

`[38;5;2m ▷ Running the 'utility-nvm-nvm' provisioner...[0m
 * Checking for NVM
 * NVM installation starting now
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13527  100 13527    0     0  50853      0 --:--:-- --:--:-- --:--:-- 50662
=> Downloading nvm from git to '/root/.nvm'

=> Cloning into '/root/.nvm'...
=> Compressing and cleaning up git repository

=> Appending nvm source string to /root/.bashrc
=> Appending bash_completion source string to /root/.bashrc
=> You currently have modules installed globally with `npm`. These will no
=> longer be linked to the active version of Node when you install a new node
=> with `nvm`; and they may (depending on how you construct your `$PATH`)
=> override the binaries of modules installed with `nvm`:

/usr/lib
├── grunt@1.2.0
├── grunt-cli@1.3.2
├── grunt-cssjanus@0.5.0
├── grunt-rtlcss@2.0.2
├── grunt-sass@3.1.0
└── npm-check-updates@7.0.1
=> If you wish to uninstall them at a later point (or re-install them under your
=> `nvm` Nodes), you can remove them from the system Node as follows:

     $ nvm use system
     $ npm uninstall -g a_module

=> Close and reopen your terminal to start using nvm or run the following to use it now:

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
 * NVM installed
/srv/provision/utilities/nvm/nvm/provision.sh: line 28: nvm: command not found
 * NVM default set to system default
[38;5;2m ✔ The 'utility-nvm-nvm' provisioner completed in 3 seconds.[0m
`
# Output
`==> default: Running provisioner: utility-nvm-nvm (shell)...
    default: Running: /tmp/vagrant-shell20200706-9379-1sqpgci.sh
    default:  ▷ Running the 'utility-nvm-nvm' provisioner...
    default:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
    default:     
    default:                              Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0     
    default:  0 --:--:-- --:--:-- --:--:--     0
100 13527  100 13527    0     0  50853      0 --:--:-- --:--:-- --:--:-- 50662
    default: Cloning into '/root/.nvm'...
    default: /srv/provision/utilities/nvm/nvm/provision.sh: line 28: nvm: command not found
    default:  ✔ The 'utility-nvm-nvm' provisioner completed in 3 seconds.
`

**Comment by tomjn** [comment]
I suspect it's installed it to the `root` user not the `vagrant` user, most likely `noroot` is needed

**Comment by Mte90** [comment]
I tested further, with a reboot found the utility, this because require that a sh file is running on bashrc profile from VVV itself (the other pr).

So I think that is better that on install this `nvm.sh` file is executed so after the provision the tool is available and don't need a reboot.

**Comment by Mte90** [comment]
I think that needs some testing from someone else

**Pull request merged**
