### PR TITLE
WIP: provision phpmyadmin via composer

### PR DESCRIPTION
**Pull request by cfoellmann**
this provisions phpmyadmin via composer. BUT this is a package maintained by me because the official package does not provide language files.
reduces provision time (composer).

# Problem
older installs? What happens if `database-admin` is already present?

### CODE REVIEW

**Comment by tomjn** [comment]
We should be able to use `phpmyadmin/phpmyadmin` via the official composer repo, which uses the same tarballs we currently use to install it:

```
composer create-project phpmyadmin/phpmyadmin --repository-url=https://www.phpmyadmin.net/packages.json --no-dev
```

These have the benefit of already coming with the languages bundled

**Comment by cfoellmann** [comment]
@tomjn yes. Now we can. This is very old and back then the composer repo did not include languages-

**Comment by tomjn** [comment]
We can also test for a composer install via `composer status` which will return a bad response we can test for. If so delete the folder and run composer, we'll need to add ` .` to the end of the command though

**Comment by tomjn** [comment]
@cfoellmann what are your thoughts on these latest changes?

**Comment by tomjn** [comment]
Closes https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1536

**Comment by Mte90** [comment]
Seems that in my installation this updated is not happening.
I tried also a `composer update --no-autoloader` manually on the folder but the files are of 4.7.0.
As I can see there is a file `RELEASE-DATE-4.7.0` inside the folder, maybe is better to use this one to detected if phpmyadmin is installed because `composer status` in my case say: `No local changes`

**Comment by tomjn** [comment]
if it says no local changes we can assume it's a composer install, I wonder if the problem is that we're using create-project? Testing for `RELEASE-DATA-4.7.0` won't work once it moves to 4.8.0 etc

**Comment by Mte90** [comment]
I mean for people with old VVV when they will run this maybe phpmyadmin will not updated, so a check about that file or version to erase everything can be a solution.

**Comment by cfoellmann** [comment]
Composer is so fast. We should just erase and deploy new 😬

**Comment by tomjn** [comment]
Done, time to test

**Comment by Mte90** [comment]
Tested and worked!

**Pull request merged**
